include("UtilityFunctionsModule.jl")
include("AlgorithmsEasyModule.jl")
include("AlgorithmsMediumModule.jl")
include("AlgorithmsHardModule.jl")
include("DataStructuresEasyModule.jl")
include("SinglyLinkedListModule.jl")