include("UtilityFunctionsModule.jl")
include("AlgorithmsEasyModule.jl")
include("AlgorithmsMediumModule.jl")
include("AlgorithmsHardModule.jl")
include("SinglyLinkedListModule.jl")
include("DataStructuresEasyModule.jl")
include("MathematicsEasyModule.jl")
